#!/usr/bin/env sh

# Scripting addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar all:32:0

yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 8

yabai -m config window_shadow float
yabai -m config window_opacity off
yabai -m config active_window_border_topmost off

borders &

# unmanaged / floating apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Software Update$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add title="^(Preferences|Settings|Setting)$" manage=off

echo "yabai configuration loaded.."
