#!/bin/bash

options=(
  style=round
  width=6.0
  hidpi=off
  active_color="gradient(top_left=0xff88c0d0,bottom_right=0xff81a1c1)"
  inactive_color=0xc03b4252
  background_color=0x302e3440
)

borders "${options[@]}"
